### PR TITLE
Amazon updated their cert signing, this fixes it

### PR DESCRIPTION
**Pull request by spunkedy**
Hello,

On the 28th Amazon changed their signing. This fixes it based upon the root ca list
[here](https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/?mkt_tok=eyJpIjoiTkdaa05UVTJabUpsT0RSaSIsInQiOiI1dmhhZHpxVHRlRnZuZktWRDVGNk44czlCT21odWxDeWxrVmZSbHNoVWdcLzZsdTh3clQwNEd4N1ZEYXhrZDFjY085R0w2aVwvUTFtV3pEd0Yxa1JvalhzTlVDV1Z0SXZvc01ZQU5zbnMweW1PdWIwcXBTMU9kUjNcL29KMDhMcm9taiJ9)

### CODE REVIEW

**Comment by grahac** [comment]
Thanks so much for making these changes!  The one thing I noticed is your last certificate does not match that of Amazon's on this page.  Maybe they changed it since you submitted?  Can you double-check?  Otherwise looks good! 

https://www.amazontrust.com/repository/

**Comment by hauntedhost** [comment]
Could you push a `0.1.6` to hex.pm with this fix if you get a chance?

**Comment by grahac** [comment]
Ok. pushed.  That was much easier said than done.  To get it to work I had to upgrade to minimum Elixir 1.7 and modify the ex_docs dependencies appropriately.  (I'm sure there was another way to do it but it kept segfaulting on my computer if I used a previous elixir version .)

**Comment by hauntedhost** [comment]
Thanks!

**Pull request merged**
